name: workflow-desc
channels:
  - conda-forge
  - bioconda
dependencies:
  - python =3.10
  - jupyterlab
  - numpy
  - matplotlib
  - pandas
  - pyyaml
  - nextflow
  - lammps
  - cwltool
  - pyiron_atomistics
  - pyiron
  - pyiron_gpl
  - pyiron-data
  - openmpi
  - mpi4py
  - lammps =2022.06.23=*openmpi*_16
  - snakemake
  - pyiron_contrib =0.1.12
  - jupyterlab
  - jupyter-book
